SELECT
    E.EMPLOYEE_ID,
    E.JOB_ID,
    E.MANAGER_ID,
    E.DEPARTMENT_ID,
    E.EMAIL,
    D.LOCATION_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.SALARY,
    E.COMMISSION_PCT,
    D.DEPARTMENT_NAME
FROM
    ${database}.HR.EMPLOYEES E
    INNER JOIN ${database}.HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
